import {carbonCopy} from './carbon';
export const languages = ['sv', 'en', 'de'] as const;
export type Lang = typeof languages[number];
export const slugs = ['biobruk', 'teknik', 'aktivt-kol', 'vatgas', 'etableringar', 'om-biona', 'partners', 'kontakt'] as const;
export type Slug = typeof slugs[number];
export type Article = { label: string; title: string; intro: string; sections: { title: string; body: string }[] };
export const copy = {
sv: {
 nav: ['Biobruk', 'Tekniken', 'Aktivt kol', 'Vätgas', 'Etableringar', 'Om Biona', 'Partners', 'Kontakt'],
 menu: 'Öppna meny', close: 'Stäng meny', skip: 'Till innehållet', contact: 'Prata med oss', explore: 'Upptäck Biobruk', more: 'Läs mer',
 eyebrow: 'BIONA · SVENSKA RESURSER', hero: ['Från svensk skog', 'till renare vatten.'],
 intro: 'Biona utvecklar aktivt kol av svensk skog, utan tillsatser och med ångaktivering, för rening av PFAS och läkemedelsrester. Vårt mål är 100 % fossilfritt aktivt kol – för renare vatten, lokal försörjning och ett beredskapsstarkt Sverige.',
 concept: 'Konceptvisualisering av ett framtida Biobruk.', scroll: 'Utforska kretsloppet',
 purposeLabel: 'DET HÄR ÄR BIONA', purpose: 'En råvara. Fler möjligheter.', purposeBody: 'Lokala resurser kan göra större nytta. Vi börjar med aktivt kol för rening av vatten och industriella flöden – och utvecklar en modell där material, energi och kompetens samverkar.',
 loopLabel: 'FRÅN RÅVARA TILL SAMHÄLLSNYTTA', loop: ['Lokal biomassa', 'Termisk förädling', 'Aktivt kol', 'Rening & användning', 'Utveckling av returflöden'],
 loopBody: ['Utvalda träbaserade råvaror', 'Pyrolys och ångaktivering', 'Poröst material för rening', 'Vatten och industriella flöden', 'Återanvändning och regenerering utreds'],
 focusLabel: 'RESULTATEN BAKOM SIFFRORNA', focusTitle: 'Stor inre yta.\nTydliga testvärden.', focusBody: 'Vi genomför omfattande kvalitetstester av vårt aktiva kol för PFAS-rening och bjuder in kommuner till innovationsupphandling och provning. Planerad försäljningsstart är november 2026. Två rapporterade materialtester visar en BET-yta på 1 250–1 280 m²/g.', evidence: 'Underlag: Bionas uppgifter om två materialtester. Fullständiga labbrapporter och en internationell jämförelse är ännu inte publicerade här.', heroProductLink: 'Upptäck vårt aktiva kol', heroStatus: 'Omfattande kvalitetstester pågår. Planerad försäljningsstart november 2026.', materialFacts: ['Svensk skog', 'Utan tillsatser', 'Ångaktiverat'],
 bet: 'BET-yta i två rapporterade tester', betNote: 'm²/g · avser testmaterial, inte en generell leveransgaranti', status: 'RAPPORTERADE MATERIALTESTER',
 productsLabel: 'ETT KRETSLOPP SOM VÄXER', productsTitle: 'Vi börjar där vi kan skapa nytta.', cards: [
  ['Aktivt kol', 'För PFAS-rening. Kommuner bjuds in till provning medan omfattande kvalitetstester pågår.', 'Planerad säljstart · november 2026'],
  ['Biobruk', 'En sammanhängande modell för råvara, material och energi.', 'Industriell vision'],
  ['Vätgas', 'Nästa utvecklingssteg med elektrolys som planerad teknik.', 'Under utveckling']],
 visionLabel: 'VISION 20/20', visionTitle: 'Lokala rötter.\nIndustriell räckvidd.', visionBody: 'Vår långsiktiga ambition är 20 Biobruk på 20 strategiska orter. Etableringsarbetet utgår från råvara, logistik, infrastruktur och kundbehov.', visionNote: 'Visionen beskriver ett mål. Orter och anläggningar är inte beslutade.', regionsLabel: 'ETABLERINGSREGIONER UNDER UTVÄRDERING',
 peopleLabel: 'MÄNNISKORNA BAKOM', peopleTitle: 'Från idé till industri.\nTillsammans.', peopleBody: 'Vi förenar ledarskap, struktur och industriell utveckling för att ta Bionas nästa steg.', roles: ['Medgrundare · VD & styrelseordförande', 'Medgrundare · Operativ chef, COO', 'Medgrundare · Administrativ chef', 'Kommersiell utveckling & affärsutveckling', 'Strategisk utveckling & säkerhet'],
 ctaLabel: 'BYGG NÄSTA STEG MED OSS', cta: 'En renare värld\nbörjar med en dialog.', ctaBody: 'Är du kund, industripartner, investerare eller representerar en etableringsort? Låt oss prata om möjligheterna.',
 footer: 'Lokala råvaror. Starkare samhällen. Renare framtid.', rights: 'Alla rättigheter förbehållna.', note: 'Produktutveckling och etableringar pågår. Visioner och kapacitetsmål utgör inte leveransåtaganden.',
 detailLabel: 'FÖRDJUPNING', next: 'Diskutera nästa steg', emailLabel: 'Kontakta ledningen', emailNote: 'Beskriv gärna ditt intresse och hur vi kan samarbeta.', privacy: 'Webbplatsen använder inga egna analyscookies. Vimeo laddas först när du startar filmen.',
 regions: ['Norr', 'Söder', 'Väst', 'Öst'], regionBodies: ['Råvaror, logistik och lokala samarbeten bedöms inför möjliga etableringar.', 'Kundbehov och transportförbindelser är delar av etableringsunderlaget.', 'Industriella flöden och möjligheter till samverkan utvärderas.', 'Infrastruktur och distribution vägs samman med råvaru- och kundbehov.'],
 articles: {
 'biobruk': {label: 'BIONA BIOBRUK', title: 'Ett kretslopp.\nFlera möjligheter.', intro: 'Biobruk är Bionas modell för att knyta samman lokala träbaserade råvaror, industriell förädling och användbara produkter.', sections: [{title:'Först aktivt kol',body:'Det första produktfokuset är aktivt kol. Arbetet omfattar råvaruhantering, termisk förädling, ångaktivering och verifiering tillsammans med kunder och teknikpartners.'},{title:'Material och energi i samspel',body:'Den långsiktiga modellen inkluderar nyttiggörande av processenergi och utveckling av vätgasproduktion genom elektrolys. Varje del behöver dimensioneras och verifieras för den aktuella anläggningen.'},{title:'Utveckling steg för steg',body:'Biobruk utvecklas etappvis. Testning och kundverifiering föregår större industriell etablering. Möjligheter till returflöden och regenerering av använt aktivt kol utreds.'}]},
 'teknik': {label:'TEKNIKEN',title:'Från råvara\ntill funktion.',intro:'Bionas tekniska utveckling fokuserar på sambandet mellan råvarans kvalitet, termisk behandling och det aktiva kolets egenskaper.',sections:[{title:'Råvaran sätter förutsättningarna',body:'Träbaserat material väljs och förbereds med hänsyn till bland annat fukthalt, bark och föroreningar.'},{title:'Pyrolys och ångaktivering',body:'Genom termisk förädling och aktivering med ånga utvecklas kolets porstruktur. Temperatur, uppehållstid och processförhållanden behöver anpassas till önskad slutprodukt.'},{title:'Mätningar som stödjer nästa steg',body:'BET-yta, askhalt och funktion i den avsedda reningsprocessen är viktiga mått. Resultat från enskilda tester behöver följas av kundspecifik verifiering och överenskomna produktspecifikationer.'}]},
 'aktivt-kol': carbonCopy.sv.article,
 'vatgas': {label:'VÄTGAS',title:'Nästa steg\ni vår utveckling.',intro:'Vätgas är en del av Bionas långsiktiga industrimodell. Den planerade produktionsvägen är elektrolys.',sections:[{title:'Elektrolys som planerad teknik',body:'Elektrolys använder el för att dela vatten i vätgas och syre. Bionas planerade vätgasproduktion behöver därför säkrad elförsörjning, vattenhantering och teknisk dimensionering.'},{title:'Samspel med Biobruk',body:'Möjligheter till energi- och värmeintegration utvärderas. Spillvärme kan bidra till andra processer, men ersätter inte elektrolysens behov av el.'},{title:'En utvecklingsetapp',body:'Teknikval, kapacitet, klimatprestanda, investering och tidplan utreds. Vätgas presenteras som ett planerat utvecklingsområde och ännu inte som en produkt till försäljning.'}]},
 'etableringar': {label:'ETABLERINGAR · VISION 20/20',title:'Lokala nav.\nNytta i hela Sverige.',intro:'Vi utvecklar ett nätverk med möjliga Biobruk i norr, söder, väst och öst. Terminaler, kunder och partners kan knyta samman råvaror, industri och samhällsnytta.',sections:[{title:'Råvara och logistik',body:'Närhet till lämplig biomassa och möjligheter till väg-, järnvägs- eller hamntransporter är centrala i etableringsarbetet.'},{title:'Industriella förutsättningar',body:'Markens lämplighet, tillstånd, el, vatten och möjliga samarbeten bedöms för varje kandidat. En region som utvärderas är inte en beslutad etablering.'},{title:'Vision 20/20',body:'20 Biobruk på 20 strategiska orter är en långsiktig ambition. Utbyggnad förutsätter verifierad teknik, finansiering, avtal, tillstånd och fungerande leveranskedjor.'}]},
 'om-biona': {label:'OM BIONA GROUP',title:'Människorna\nbakom förändringen.',intro:'Biona Group AB utvecklar en cirkulär industrimodell med lokala råvaror och aktivt kol som första produktfokus.',sections:[{title:'Vårt uppdrag',body:'Vi vill skapa användbara produkter av träbaserade resurser och bygga industriell kapacitet där förutsättningarna finns.'},{title:'Så arbetar vi',body:'Vi utvecklar stegvis tillsammans med teknikpartners, kunder och etableringsaktörer. Materialtester, kundverifiering och genomförbarhet styr vilka investeringar som kan tas vidare.'},{title:'Hållbarhet behöver belägg',body:'Vår ambition är resurseffektiva flöden och lokal samhällsnytta. Klimatpåverkan, råvarans ursprung och energianvändning behöver utvärderas för respektive process och anläggning.'}]},
 'partners': {label:'KUNDER, PARTNERS & INVESTERARE',title:'Nästa steg\nbygger vi tillsammans.',intro:'Bionas aktuella arbete fokuserar på verifiering, kunddialog och förberedelser för industriell uppskalning.',sections:[{title:'För kunder',body:'Vi vill diskutera reningsbehov, materialkrav och provningsupplägg. Kundens processförhållanden och mätbara resultat är utgångspunkten.'},{title:'För industri- och etableringspartners',body:'Vi söker dialog om råvaruflöden, teknik, logistik och lämpliga etableringsmiljöer. Samverkan formas efter varje parts roll och förutsättningar.'},{title:'För investerare',body:'Nästa milstolpar är fortsatt teknisk verifiering, kundprovning och avtal samt underlag för investering och etablering. Fördjupat material och finansieringsdialog hanteras genom direktkontakt med ledningen.'}]},
 'kontakt': {label:'KONTAKT',title:'Från första samtal\ntill nästa möjlighet.',intro:'Berätta om din verksamhet, ditt reningsbehov eller dina idéer för samarbete. Vi tar dialogen vidare tillsammans.',sections:[{title:'Kunder och teknikpartners',body:'Beskriv användningsområde, tänkt volym och eventuella krav på material eller reningsprestanda.'},{title:'Etableringar och investeringar',body:'Berätta om platsens förutsättningar eller ditt intresse för Bionas utveckling. Ledningen ansvarar för den fortsatta dialogen.'}]}
 }
},
en: {
 nav:['Biobruk','Technology','Activated carbon','Hydrogen','Locations','About Biona','Partners','Contact'],menu:'Open menu',close:'Close menu',skip:'Skip to content',contact:'Talk to us',explore:'Discover Biobruk',more:'Read more',
 eyebrow:'BIONA · SWEDISH RESOURCES',hero:['From Swedish forests','to cleaner water.'],intro:'Biona develops activated carbon from Swedish forests, without additives and using steam activation, for the treatment of PFAS and pharmaceutical residues. Our goal is 100% fossil-free activated carbon – for cleaner water, local supply and a resilient Sweden.',concept:'Concept visualisation of a future Biobruk.',scroll:'Explore the loop',
 purposeLabel:'THIS IS BIONA',purpose:'One resource. More possibilities.',purposeBody:'Local resources can deliver greater value. We start with activated carbon for water and industrial treatment, developing a model that connects materials, energy and expertise.',
 loopLabel:'FROM RESOURCES TO SHARED VALUE',loop:['Local biomass','Thermal processing','Activated carbon','Treatment & use','Return-flow development'],loopBody:['Selected wood-based feedstocks','Pyrolysis and steam activation','Porous material for treatment','Water and industrial streams','Reuse and regeneration under evaluation'],
 focusLabel:'THE RESULTS BEHIND THE NUMBERS',focusTitle:'Large internal surface.\nClear test values.',focusBody:'We are conducting extensive quality tests of our activated carbon for PFAS treatment and inviting municipalities to innovation procurement and testing. The planned sales launch is November 2026. Two reported material tests show a BET surface area of 1 250–1 280 m²/g.',evidence:'Source: Biona’s information on two material tests. Full laboratory reports and an international comparison are not yet published here.',heroProductLink:'Discover our activated carbon',heroStatus:'Extensive quality testing is underway. Planned sales launch November 2026.',materialFacts:['Swedish forests','No additives','Steam activated'],bet:'BET surface area in two reported tests',betNote:'m²/g · test material, not a general supply guarantee',status:'REPORTED MATERIAL TESTS',
 productsLabel:'A GROWING CIRCULAR MODEL',productsTitle:'Starting where we can create value.',cards:[['Activated carbon','For PFAS treatment. Municipal testing dialogue and extensive quality tests are underway.','Planned sales launch · November 2026'],['Biobruk','An integrated model for resources, materials and energy.','Industrial vision'],['Hydrogen','The next development stage, with electrolysis as the planned technology.','In development']],
 visionLabel:'VISION 20/20',visionTitle:'Local roots.\nIndustrial reach.',visionBody:'Our long-term ambition is 20 Biobruk facilities in 20 strategic locations. Development is guided by resources, logistics, infrastructure and customer needs.',visionNote:'The vision is a goal. Locations and facilities have not been decided.',regionsLabel:'REGIONS UNDER EVALUATION',
 peopleLabel:'THE PEOPLE BEHIND BIONA',peopleTitle:'From idea to industry.\nTogether.',peopleBody:'We bring leadership, structure and industrial development together to take Biona forward.',roles:['Co-founder · Chairman & CEO','Co-founder · COO','Co-founder · Head of Administration','Commercial & Business Development','Strategic Development & Security'],
 ctaLabel:'BUILD THE NEXT STEP WITH US',cta:'A cleaner world\nstarts with a conversation.',ctaBody:'A customer, industrial partner, investor or potential host region? Let’s discuss the possibilities.',footer:'Local resources. Stronger communities. A cleaner future.',rights:'All rights reserved.',note:'Product and location development is ongoing. Visions and capacity targets are not supply commitments.',detailLabel:'EXPLORE',next:'Discuss the next step',emailLabel:'Contact the leadership team',emailNote:'Tell us about your interests and how we could work together.',privacy:'This website uses no first-party analytics cookies. Vimeo loads only when you start the film.',
 regions:['North','South','West','East'],regionBodies:['Resources, logistics and local collaboration are assessed for potential locations.','Customer demand and transport connections inform location evaluation.','Industrial flows and opportunities for collaboration are evaluated.','Infrastructure and distribution are considered alongside resource and customer needs.'],
 articles:{
 'biobruk':{label:'BIONA BIOBRUK',title:'One circular model.\nMore possibilities.',intro:'Biobruk is Biona’s model for connecting local wood-based resources, industrial processing and useful products.',sections:[{title:'Activated carbon first',body:'Our first product focus is activated carbon. Development covers feedstock preparation, thermal processing, steam activation and validation with customers and technology partners.'},{title:'Connecting materials and energy',body:'The long-term model includes using process energy and developing hydrogen production through electrolysis. Each element requires site-specific design and validation.'},{title:'Step-by-step development',body:'Testing and customer validation precede larger industrial investments. Return flows and regeneration of spent activated carbon are under evaluation.'}]},
 'teknik':{label:'TECHNOLOGY',title:'From feedstock\nto function.',intro:'Our technical development connects feedstock quality, thermal treatment and the properties of activated carbon.',sections:[{title:'Feedstock matters',body:'Wood-based materials are selected and prepared with attention to moisture, bark and contaminants.'},{title:'Pyrolysis and steam activation',body:'Thermal processing and steam activation develop the carbon’s pore structure. Temperature, residence time and process conditions must suit the intended product.'},{title:'Measurements guide the next step',body:'BET surface area, ash content and application performance are key measures. Individual tests must be followed by customer-specific validation and agreed product specifications.'}]},
 'aktivt-kol': carbonCopy.en.article,
 'vatgas':{label:'HYDROGEN',title:'The next stage\nof our development.',intro:'Hydrogen forms part of Biona’s long-term industrial model. Electrolysis is the planned production route.',sections:[{title:'Electrolysis as the planned technology',body:'Electrolysis uses electricity to split water into hydrogen and oxygen. The planned production requires electricity supply, water management and technical design.'},{title:'Integration with Biobruk',body:'Energy and heat integration opportunities are being assessed. Waste heat can support other processes but does not replace the electricity needed for electrolysis.'},{title:'A development stage',body:'Technology, capacity, climate performance, investment and scheduling are under evaluation. Hydrogen is a planned development area, not yet a product for sale.'}]},
 'etableringar':{label:'LOCATIONS · VISION 20/20',title:'Local hubs.\nValue across Sweden.',intro:'We are developing a network with potential Biobruk hubs across northern, southern, western and eastern Sweden. Terminals, customers and partners can connect resources, industry and shared value.',sections:[{title:'Feedstock and logistics',body:'Proximity to suitable biomass and road, rail or port connections are central to location development.'},{title:'Industrial conditions',body:'Land suitability, permits, electricity, water and potential collaborations are assessed for each candidate. A region under evaluation is not a confirmed facility.'},{title:'Vision 20/20',body:'20 Biobruk facilities in 20 strategic locations is a long-term ambition. Expansion depends on validated technology, financing, agreements, permits and functioning supply chains.'}]},
 'om-biona':{label:'ABOUT BIONA GROUP',title:'The people\nbehind the change.',intro:'Biona Group AB is developing a circular industrial model with local resources and activated carbon as its first product focus.',sections:[{title:'Our purpose',body:'We aim to create useful products from wood-based resources and build industrial capacity where conditions support it.'},{title:'Our approach',body:'We develop step by step with technology partners, customers and potential host regions. Material tests, customer validation and feasibility guide investment decisions.'},{title:'Sustainability requires evidence',body:'Our ambition is resource-efficient flows and local community value. Climate impact, resource origin and energy use must be evaluated for each process and facility.'}]},
 'partners':{label:'CUSTOMERS, PARTNERS & INVESTORS',title:'The next step\nis a shared one.',intro:'Our current work focuses on validation, customer dialogue and preparations for industrial scale-up.',sections:[{title:'For customers',body:'We discuss treatment needs, material requirements and testing programmes. Customer process conditions and measurable results are the starting point.'},{title:'For industrial and location partners',body:'We welcome dialogue on feedstock, technology, logistics and suitable industrial settings. Collaboration is shaped by each party’s role and conditions.'},{title:'For investors',body:'Next milestones include further technical validation, customer testing and agreements, and investment and location planning. Detailed materials and financing discussions are handled directly by the leadership team.'}]},
 'kontakt':{label:'CONTACT',title:'From a first conversation\nto the next opportunity.',intro:'Tell us about your business, treatment needs or ideas for collaboration. We can take the dialogue forward together.',sections:[{title:'Customers and technology partners',body:'Describe your application, intended volume and any requirements for the material or treatment performance.'},{title:'Locations and investment',body:'Share the conditions at your location or your interest in Biona’s development. Our leadership team handles the continuing dialogue.'}]}
 }
},
de: {
 nav:['Biobruk','Technologie','Aktivkohle','Wasserstoff','Standorte','Über Biona','Partner','Kontakt'],menu:'Menü öffnen',close:'Menü schließen',skip:'Zum Inhalt',contact:'Kontakt aufnehmen',explore:'Biobruk entdecken',more:'Mehr erfahren',
 eyebrow:'BIONA · SCHWEDISCHE RESSOURCEN',hero:['Aus schwedischen Wäldern','zu saubererem Wasser.'],intro:'Biona entwickelt Aktivkohle aus schwedischen Wäldern, ohne Zusatzstoffe und mit Dampfaktivierung, zur Reinigung von PFAS und Arzneimittelrückständen. Unser Ziel ist 100 % fossilfreie Aktivkohle – für saubereres Wasser, lokale Versorgung und ein widerstandsfähiges Schweden.',concept:'Konzeptvisualisierung eines zukünftigen Biobruk.',scroll:'Den Kreislauf entdecken',
 purposeLabel:'DAS IST BIONA',purpose:'Ein Rohstoff. Mehr Möglichkeiten.',purposeBody:'Lokale Ressourcen können mehr Nutzen schaffen. Wir beginnen mit Aktivkohle für Wasseraufbereitung und industrielle Stoffströme und entwickeln ein Modell, das Materialien, Energie und Know-how verbindet.',
 loopLabel:'VOM ROHSTOFF ZUM GESELLSCHAFTLICHEN NUTZEN',loop:['Lokale Biomasse','Thermische Veredelung','Aktivkohle','Aufbereitung & Nutzung','Entwicklung von Rückflüssen'],loopBody:['Ausgewählte holzbasierte Rohstoffe','Pyrolyse und Dampfaktivierung','Poröses Material zur Reinigung','Wasser und industrielle Stoffströme','Wiederverwendung und Regeneration werden geprüft'],
 focusLabel:'DIE ERGEBNISSE HINTER DEN ZAHLEN',focusTitle:'Große innere Oberfläche.\nKlare Testwerte.',focusBody:'Wir führen umfangreiche Qualitätstests unserer Aktivkohle für die PFAS-Reinigung durch und laden Kommunen zur Innovationsbeschaffung und zu Tests ein. Der geplante Verkaufsstart ist November 2026. Zwei berichtete Materialtests zeigen eine BET-Oberfläche von 1 250–1 280 m²/g.',evidence:'Quelle: Bionas Angaben zu zwei Materialtests. Vollständige Laborberichte und ein internationaler Vergleich sind hier noch nicht veröffentlicht.',heroProductLink:'Unsere Aktivkohle entdecken',heroStatus:'Umfangreiche Qualitätstests laufen. Geplanter Verkaufsstart November 2026.',materialFacts:['Schwedische Wälder','Ohne Zusatzstoffe','Dampfaktiviert'],bet:'BET-Oberfläche in zwei berichteten Tests',betNote:'m²/g · Testmaterial, keine allgemeine Liefergarantie',status:'BERICHTETE MATERIALTESTS',
 productsLabel:'EIN WACHSENDES KREISLAUFMODELL',productsTitle:'Wir beginnen dort, wo wir Nutzen schaffen können.',cards:[['Aktivkohle','Für PFAS-Reinigung. Kommunaler Testdialog und umfangreiche Qualitätstests laufen.','Geplanter Verkaufsstart · November 2026'],['Biobruk','Ein integriertes Modell für Rohstoffe, Materialien und Energie.','Industrielle Vision'],['Wasserstoff','Nächster Entwicklungsschritt mit Elektrolyse als geplanter Technologie.','In Entwicklung']],
 visionLabel:'VISION 20/20',visionTitle:'Lokale Wurzeln.\nIndustrielle Reichweite.',visionBody:'Unsere langfristige Ambition sind 20 Biobruk-Anlagen an 20 strategischen Standorten. Rohstoffe, Logistik, Infrastruktur und Kundenbedarf bestimmen die Entwicklung.',visionNote:'Die Vision beschreibt ein Ziel. Standorte und Anlagen sind nicht beschlossen.',regionsLabel:'REGIONEN IN DER BEWERTUNG',
 peopleLabel:'DIE MENSCHEN HINTER BIONA',peopleTitle:'Von der Idee zur Industrie.\nGemeinsam.',peopleBody:'Wir verbinden Führung, Struktur und industrielle Entwicklung, um Biona voranzubringen.',roles:['Mitgründer · CEO & Verwaltungsratsvorsitzender','Mitgründerin · COO','Mitgründerin · Leiterin Administration','Vertrieb & Geschäftsentwicklung','Strategische Entwicklung & Sicherheit'],
 ctaLabel:'GESTALTEN SIE DEN NÄCHSTEN SCHRITT MIT UNS',cta:'Eine sauberere Welt\nbeginnt mit einem Gespräch.',ctaBody:'Kunde, Industriepartner, Investor oder potenzielle Standortregion? Lassen Sie uns über die Möglichkeiten sprechen.',footer:'Lokale Rohstoffe. Stärkere Gemeinschaften. Eine sauberere Zukunft.',rights:'Alle Rechte vorbehalten.',note:'Produkt- und Standortentwicklung laufen. Visionen und Kapazitätsziele sind keine Lieferzusagen.',detailLabel:'MEHR ERFAHREN',next:'Den nächsten Schritt besprechen',emailLabel:'Kontakt zur Geschäftsleitung',emailNote:'Beschreiben Sie Ihr Interesse und mögliche Formen der Zusammenarbeit.',privacy:'Diese Website verwendet keine eigenen Analyse-Cookies. Vimeo wird erst beim Start des Films geladen.',
 regions:['Nord','Süd','West','Ost'],regionBodies:['Rohstoffe, Logistik und lokale Zusammenarbeit werden für mögliche Standorte bewertet.','Kundenbedarf und Transportverbindungen fließen in die Standortbewertung ein.','Industrielle Stoffströme und Kooperationsmöglichkeiten werden geprüft.','Infrastruktur und Verteilung werden mit Rohstoff- und Kundenbedarf zusammen betrachtet.'],
 articles:{
 'biobruk':{label:'BIONA BIOBRUK',title:'Ein Kreislauf.\nMehr Möglichkeiten.',intro:'Biobruk ist Bionas Modell zur Verbindung lokaler holzbasierter Rohstoffe, industrieller Verarbeitung und nutzbarer Produkte.',sections:[{title:'Zuerst Aktivkohle',body:'Der erste Produktschwerpunkt ist Aktivkohle. Die Entwicklung umfasst Rohstoffvorbereitung, thermische Verarbeitung, Dampfaktivierung und Validierung mit Kunden und Technologiepartnern.'},{title:'Materialien und Energie verbinden',body:'Das langfristige Modell umfasst die Nutzung von Prozessenergie und die Entwicklung der Wasserstoffproduktion durch Elektrolyse. Jeder Teil erfordert standortspezifische Auslegung und Validierung.'},{title:'Schrittweise Entwicklung',body:'Tests und Kundenvalidierung gehen größeren industriellen Investitionen voraus. Rückflüsse und die Regeneration gebrauchter Aktivkohle werden geprüft.'}]},
 'teknik':{label:'TECHNOLOGIE',title:'Vom Rohstoff\nzur Funktion.',intro:'Unsere technische Entwicklung verbindet Rohstoffqualität, thermische Behandlung und die Eigenschaften der Aktivkohle.',sections:[{title:'Der Rohstoff ist entscheidend',body:'Holzbasierte Materialien werden mit Blick auf Feuchtigkeit, Rinde und Verunreinigungen ausgewählt und vorbereitet.'},{title:'Pyrolyse und Dampfaktivierung',body:'Thermische Verarbeitung und Dampfaktivierung entwickeln die Porenstruktur. Temperatur, Verweilzeit und Prozessbedingungen müssen zum vorgesehenen Produkt passen.'},{title:'Messungen leiten den nächsten Schritt',body:'BET-Oberfläche, Aschegehalt und Leistung im vorgesehenen Prozess sind wichtige Größen. Einzeltests erfordern anschließende kundenspezifische Validierung und vereinbarte Produktspezifikationen.'}]},
 'aktivt-kol': carbonCopy.de.article,
 'vatgas':{label:'WASSERSTOFF',title:'Der nächste Schritt\nin unserer Entwicklung.',intro:'Wasserstoff ist Teil von Bionas langfristigem Industriemodell. Elektrolyse ist der geplante Produktionsweg.',sections:[{title:'Elektrolyse als geplante Technologie',body:'Elektrolyse nutzt Strom, um Wasser in Wasserstoff und Sauerstoff zu spalten. Die geplante Produktion erfordert Stromversorgung, Wassermanagement und technische Auslegung.'},{title:'Integration mit Biobruk',body:'Möglichkeiten zur Energie- und Wärmeintegration werden bewertet. Abwärme kann andere Prozesse unterstützen, ersetzt aber nicht den Strombedarf der Elektrolyse.'},{title:'Eine Entwicklungsphase',body:'Technologie, Kapazität, Klimabilanz, Investition und Zeitplan werden geprüft. Wasserstoff ist ein geplantes Entwicklungsfeld und noch kein Produkt zum Verkauf.'}]},
 'etableringar':{label:'STANDORTE · VISION 20/20',title:'Lokale Knotenpunkte.\nNutzen für ganz Schweden.',intro:'Wir entwickeln ein Netzwerk mit möglichen Biobruk-Anlagen im Norden, Süden, Westen und Osten Schwedens. Terminals, Kunden und Partnern können Rohstoffe, Industrie und gesellschaftlichen Nutzen verbinden.',sections:[{title:'Rohstoffe und Logistik',body:'Die Nähe zu geeigneter Biomasse und Straßen-, Schienen- oder Hafenanbindungen ist zentral für die Standortentwicklung.'},{title:'Industrielle Voraussetzungen',body:'Flächeneignung, Genehmigungen, Strom, Wasser und mögliche Kooperationen werden für jeden Kandidaten geprüft. Eine bewertete Region ist kein bestätigter Standort.'},{title:'Vision 20/20',body:'20 Biobruk-Anlagen an 20 strategischen Orten sind eine langfristige Ambition. Der Ausbau setzt validierte Technologie, Finanzierung, Verträge, Genehmigungen und funktionierende Lieferketten voraus.'}]},
 'om-biona':{label:'ÜBER BIONA GROUP',title:'Die Menschen\nhinter dem Wandel.',intro:'Biona Group AB entwickelt ein zirkuläres Industriemodell mit lokalen Rohstoffen und Aktivkohle als erstem Produktschwerpunkt.',sections:[{title:'Unser Auftrag',body:'Wir wollen nutzbare Produkte aus holzbasierten Ressourcen schaffen und industrielle Kapazität dort aufbauen, wo die Voraussetzungen stimmen.'},{title:'Unsere Arbeitsweise',body:'Wir entwickeln schrittweise mit Technologiepartnern, Kunden und potenziellen Standortregionen. Materialtests, Kundenvalidierung und Machbarkeit leiten Investitionsentscheidungen.'},{title:'Nachhaltigkeit braucht Nachweise',body:'Unsere Ambition sind ressourceneffiziente Stoffströme und lokaler gesellschaftlicher Nutzen. Klimawirkung, Rohstoffherkunft und Energiebedarf müssen je Prozess und Anlage bewertet werden.'}]},
 'partners':{label:'KUNDEN, PARTNER & INVESTOREN',title:'Den nächsten Schritt\ngestalten wir gemeinsam.',intro:'Unsere aktuelle Arbeit konzentriert sich auf Validierung, Kundendialog und die Vorbereitung der industriellen Skalierung.',sections:[{title:'Für Kunden',body:'Wir besprechen Reinigungsbedarf, Materialanforderungen und Testprogramme. Prozessbedingungen und messbare Ergebnisse beim Kunden sind der Ausgangspunkt.'},{title:'Für Industrie- und Standortpartner',body:'Wir freuen uns über Gespräche zu Rohstoffen, Technologie, Logistik und geeigneten Industriestandorten. Zusammenarbeit richtet sich nach Rolle und Voraussetzungen der Beteiligten.'},{title:'Für Investoren',body:'Die nächsten Meilensteine sind weitere technische Validierung, Kundentests und Verträge sowie Investitions- und Standortplanung. Detaillierte Unterlagen und Finanzierungsgespräche werden direkt mit der Geschäftsleitung besprochen.'}]},
 'kontakt':{label:'KONTAKT',title:'Vom ersten Gespräch\nzur nächsten Möglichkeit.',intro:'Erzählen Sie uns von Ihrem Unternehmen, Ihrem Reinigungsbedarf oder Ihren Kooperationsideen. Gemeinsam führen wir den Dialog weiter.',sections:[{title:'Kunden und Technologiepartner',body:'Beschreiben Sie Anwendung, geplante Menge und Anforderungen an Material oder Reinigungsleistung.'},{title:'Standorte und Investitionen',body:'Teilen Sie die Voraussetzungen Ihres Standorts oder Ihr Interesse an Bionas Entwicklung mit. Die Geschäftsleitung führt den weiteren Dialog.'}]}
 }
}
} as const;
export const leaders = [
 {name:'Joacim Sager', portrait:'joacim-sager.webp', email:'joacim.sager@bionagroup.se'},
 {name:'Sandra Dahlberg', portrait:'sandra-dahlberg.webp', email:'sandra.dahlberg@bionagroup.se'},
 {name:'Tina Sager', portrait:'tina-sager.webp', email:'christina.sager@bionagroup.se'},
 {name:'Joakim Söndergaard', portrait:'joakim-sondergaard.webp', email:'joacim.sondergaard@bionagroup.se'},
 {name:'Mattias Jonsson', portrait:'mattias-jonsson.webp', email:'mattias.jonsson@bionagroup.se'}
];
export function isLang(value:string): value is Lang { return languages.includes(value as Lang); }
export function isSlug(value:string): value is Slug { return slugs.includes(value as Slug); }
