import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {copy,isLang} from '@/lib/content';
import {Callout,Icon,Loop,People,Regions} from '@/components/Site';
import Film from '@/components/Film';
import {filmCopy} from '@/lib/film';
export async function generateMetadata({params}:{params:Promise<{lang:string}>}):Promise<Metadata>{const {lang}=await params;if(!isLang(lang))return {};const c=copy[lang];return {title:c.hero.join(' '),description:c.intro};}
export default async function Home({params}:{params:Promise<{lang:string}>}){
 const {lang}=await params;if(!isLang(lang))notFound();const c=copy[lang];
 return <main id="main"><section className="hero"><img className="hero-image" src="/images/biobruk-concept.webp" alt="" width="1536" height="1024" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-content"><p className="eyebrow">{c.eyebrow}</p><h1>{c.hero[0]}<br/><em>{c.hero[1]}</em></h1><p className="hero-intro">{c.intro}</p><div className="hero-buttons"><a className="button button-copper" href="#resultat">{c.resultsLink}</a><a className="button button-outline film-hero-link" href="#film"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="10" fill="none" stroke="currentColor"/><path d="m10 7 7 5-7 5Z" fill="currentColor"/></svg>{filmCopy[lang].play}</a></div></div><div className="container hero-bottom"><a href="#kretslopp" className="scroll-link"><span className="scroll-line"/>{c.scroll}</a><span className="concept-label">{c.concept}</span></div><span className="hero-side" aria-hidden="true">BIONA GROUP · CIRCULAR INDUSTRY</span></section>
 <section className="focus" id="resultat"><div className="container focus-grid"><div className="focus-copy"><p className="eyebrow">{c.focusLabel}</p><h2 className="line-break">{c.focusTitle}</h2><p>{c.focusBody}</p><ul className="material-facts">{c.materialFacts.map(fact=><li key={fact}>{fact}</li>)}</ul><Link className="text-link" href={`/${lang}/aktivt-kol/`}>{c.more} · {c.nav[2]}</Link></div><div className="measurement"><div className="carbon-mark"><Icon type="carbon"/></div><span className="eyebrow">{c.status}</span><p className="measurement-number">1 250<span>–</span>1 280</p><h3>{c.bet}</h3><p>{c.betNote}</p><p className="measurement-source">{c.evidence}</p><div className="measurement-rules"><span>BET</span><span>m²/g</span><span>02 {lang==='sv'?'tester':lang==='de'?'Tests':'tests'}</span></div></div></div></section>
 <section className="purpose section" id="kretslopp"><div className="container"><div className="section-heading"><div><p className="eyebrow">{c.purposeLabel}</p><h2>{c.purpose}</h2></div><p>{c.purposeBody}</p></div><Loop lang={lang}/></div></section>
 <Film lang={lang}/>

 <section className="products section"><div className="container"><p className="eyebrow">{c.productsLabel}</p><h2>{c.productsTitle}</h2><div className="product-grid">{c.cards.map((card,i)=><Link key={card[0]} className={`product-card product-${i}`} href={`/${lang}/${['aktivt-kol','biobruk','vatgas'][i]}/`}><span className="product-top"><span>0{i+1}</span><span>{card[2]}</span></span><div className="product-visual"><Icon type={['carbon','factory','hydrogen'][i]}/></div><div><h3>{card[0]}</h3><p>{card[1]}</p><span className="text-link">{c.more}</span></div></Link>)}</div></div></section>
 <section className="vision section"><div className="container vision-grid"><div><p className="eyebrow">{c.visionLabel}</p><h2 className="line-break">{c.visionTitle}</h2><p>{c.visionBody}</p><p className="muted small">{c.visionNote}</p><Link className="button button-outline" href={`/${lang}/etableringar/`}>{c.nav[4]}</Link></div><div><div className="vision-number" aria-hidden="true">20<span>/</span>20</div><Regions lang={lang}/></div></div></section>
 <People lang={lang}/><Callout lang={lang}/></main>;
}
